os: linux
sudo: required
dist: trusty
language: c

compiler:
  - clang
  - gcc

branches:
  only:
    - master
    - devel

before_install:
  - wget https://cmocka.org/files/1.0/cmocka-1.0.1.tar.xz
  - tar -xJvf cmocka-1.0.1.tar.xz
  - cd cmocka-1.0.1 && mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .. && make -j2 && sudo make install
  - cd ../..
  - if [ "${CC}" = "clang" ]; then sudo pip install codecov; fi

script: 
  - mkdir build && cd build ; cmake .. && make -j2 && make test

after_success:
  - if [ "${CC}" = "clang" ]; then codecov; fi

